# Generated by Django 5.2.7 on 2025-11-01 11:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва мему')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='memes/%Y/%m/%d/', verbose_name='Зображення')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov'])], verbose_name='Відео')),
                ('meme_type', models.CharField(choices=[('image', '🏞️ Фото-мем'), ('video', '🎥 Відео-мем')], default='image', max_length=20, verbose_name='Тип мему')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Перегляди')),
                ('likes', models.ManyToManyField(blank=True, related_name='meme_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Мем',
                'verbose_name_plural': 'Меми',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
