# Generated by Django 5.2.7 on 2025-11-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemeApp', '0002_remove_meme_image_remove_meme_video_meme_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_emoji',
            field=models.CharField(default='👤', max_length=10, verbose_name='Аватар (емодзі)'),
        ),
    ]
